//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Proba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public string Kontakt_telefon { get; set; }
        public int Id_lok { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
    }
}
