//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Proba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Datum_vjencanja { get; set; }
        public Nullable<double> Budzet { get; set; }
        public Nullable<int> Broj_gostiju { get; set; }
        public int Korisnik_lok { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
    }
}
