//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Proba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaProjektEntities1 : DbContext
    {
        public BazaProjektEntities1()
            : base("name=BazaProjektEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lokacija> Lokacijas { get; set; }
        public virtual DbSet<Osoba> Osobas { get; set; }
        public virtual DbSet<Podsjetnik> Podsjetniks { get; set; }
        public virtual DbSet<Stol> Stols { get; set; }
        public virtual DbSet<Trosak> Trosaks { get; set; }
        public virtual DbSet<Gost> Gosts { get; set; }
        public virtual DbSet<Kontakt> Kontakts { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
    }
}
